version: '3.8'

services:
  load_balancer:
    image: nginx
    container_name: premiser-load_balancer
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      premiser-net:
        ipv4_address: 172.24.0.2

  frontend:
    build: ./frontend
    container_name: premiser-frontend
    expose:
      - 3000
    volumes:
      - ./frontend/:/root/frontend
    networks:
      premiser-net:
        ipv4_address: 172.24.0.3
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: premiser-backend
    restart: always
    expose:
      - 5000
    volumes:
      - ./backend/:/root/backend
    networks:
      premiser-net:
        ipv4_address: 172.24.0.4
    command: python app.py

  container:
    build: ./container
    container_name: premiser-container
    environment:
      DOCKER_TLS_CERTDIR: ""
    expose:
      - 2375
      - 80
      - 28001
    volumes:
      - ./container/:/root/container
    networks:
      premiser-net:
        ipv4_address: 172.24.0.5
    privileged: true
    command: sh -c "nginx & python3 app.py & dockerd -H tcp://0.0.0.0:2375"

  database:
    image: mysql:8.0.22
    container_name: premiser-database
    restart: always
    environment:
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=password
    expose:
      - 3306
    networks:
      premiser-net:
        ipv4_address: 172.24.0.6
    volumes:
      - ./premiser.sql:/docker-entrypoint-initdb.d/premiser.sql

networks:
  premiser-net:
    external: false
    ipam:
      config:
        - subnet: 172.24.0.0/16