version: '3.8'

services:
  docker:
    image: docker:latest
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    ports:
      - 2375:2375
    networks:
      - cotton-net

  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/root/
    command: python app.py
    networks:
      - cotton-net

  react:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - cotton-net
    stdin_open: true
    tty: true


networks:
  cotton-net:
    external: false