-- MySQL Script generated by MySQL Workbench
-- 2023년 09월 05일 (화) 오전 12시 22분 26초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema premiser
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `premiser` ;

-- -----------------------------------------------------
-- Schema premiser
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `premiser` ;
USE `premiser` ;

-- -----------------------------------------------------
-- Table `premiser`.`framework`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`framework` ;

CREATE TABLE IF NOT EXISTS `premiser`.`framework` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` ENUM("framework", "database") NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`os` ;

CREATE TABLE IF NOT EXISTS `premiser`.`os` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`os_version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`os_version` ;

CREATE TABLE IF NOT EXISTS `premiser`.`os_version` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `os_id` INT NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_os_version_1_idx` (`os_id` ASC) VISIBLE,
  CONSTRAINT `fk_os_version_1`
    FOREIGN KEY (`os_id`)
    REFERENCES `premiser`.`os` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`framework_version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`framework_version` ;

CREATE TABLE IF NOT EXISTS `premiser`.`framework_version` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `framework_id` INT NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_framework_version_1_idx` (`framework_id` ASC) VISIBLE,
  CONSTRAINT `fk_framework_version_1`
    FOREIGN KEY (`framework_id`)
    REFERENCES `premiser`.`framework` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`user` ;

CREATE TABLE IF NOT EXISTS `premiser`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_name_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`project` ;

CREATE TABLE IF NOT EXISTS `premiser`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `premiser`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`container`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`container` ;

CREATE TABLE IF NOT EXISTS `premiser`.`container` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_container_info_4_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_container_info_3`
    FOREIGN KEY (`project_id`)
    REFERENCES `premiser`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`container_framework`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`container_framework` ;

CREATE TABLE IF NOT EXISTS `premiser`.`container_framework` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `container_id` INT NOT NULL,
  `version_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_container_framework_1_idx` (`container_id` ASC) VISIBLE,
  INDEX `fk_container.framework_2_idx` (`version_id` ASC) VISIBLE,
  CONSTRAINT `fk_container.framework_1`
    FOREIGN KEY (`container_id`)
    REFERENCES `premiser`.`container` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_container.framework_2`
    FOREIGN KEY (`version_id`)
    REFERENCES `premiser`.`framework_version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`container_os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`container_os` ;

CREATE TABLE IF NOT EXISTS `premiser`.`container_os` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `container_id` INT NOT NULL,
  `version_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_container.os_2_idx` (`version_id` ASC) VISIBLE,
  INDEX `fk_container.os_1_idx` (`container_id` ASC) VISIBLE,
  CONSTRAINT `fk_container.os_1`
    FOREIGN KEY (`container_id`)
    REFERENCES `premiser`.`container` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_container.os_2`
    FOREIGN KEY (`version_id`)
    REFERENCES `premiser`.`os_version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`container_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`container_info` ;

CREATE TABLE IF NOT EXISTS `premiser`.`container_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `container_id` INT NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `gpu` TINYINT NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_container.info_1_idx` (`container_id` ASC) VISIBLE,
  CONSTRAINT `fk_container.info_1`
    FOREIGN KEY (`container_id`)
    REFERENCES `premiser`.`container` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`user_password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`user_password` ;

CREATE TABLE IF NOT EXISTS `premiser`.`user_password` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `password` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auth.password_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_auth.password_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `premiser`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`project_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`project_info` ;

CREATE TABLE IF NOT EXISTS `premiser`.`project_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `subnet` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_info_1_idx` (`project_id` ASC) VISIBLE,
  UNIQUE INDEX `subnet_UNIQUE` (`subnet` ASC) VISIBLE,
  CONSTRAINT `fk_project_info_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `premiser`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`container_ports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`container_ports` ;

CREATE TABLE IF NOT EXISTS `premiser`.`container_ports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `container_id` INT NOT NULL,
  `port` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_container_ports_1_idx` (`container_id` ASC) VISIBLE,
  CONSTRAINT `fk_container_ports_1`
    FOREIGN KEY (`container_id`)
    REFERENCES `premiser`.`container` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`container_envs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`container_envs` ;

CREATE TABLE IF NOT EXISTS `premiser`.`container_envs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `container_id` INT NOT NULL,
  `k` VARCHAR(45) NOT NULL,
  `v` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_container_envs_1_idx` (`container_id` ASC) VISIBLE,
  CONSTRAINT `fk_container_envs_1`
    FOREIGN KEY (`container_id`)
    REFERENCES `premiser`.`container` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`signup_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`signup_token` ;

CREATE TABLE IF NOT EXISTS `premiser`.`signup_token` (
  `token` BLOB NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `premiser`.`user_auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiser`.`user_auth` ;

CREATE TABLE IF NOT EXISTS `premiser`.`user_auth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `refresh_token` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_auth_1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_auth_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `premiser`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `premiser`.`framework`
-- -----------------------------------------------------
START TRANSACTION;
USE `premiser`;
INSERT INTO `premiser`.`framework` (`id`, `name`, `type`) VALUES (DEFAULT, 'python', 'framework');
INSERT INTO `premiser`.`framework` (`id`, `name`, `type`) VALUES (DEFAULT, 'node', 'framework');
INSERT INTO `premiser`.`framework` (`id`, `name`, `type`) VALUES (DEFAULT, 'mysql', 'database');

COMMIT;


-- -----------------------------------------------------
-- Data for table `premiser`.`os`
-- -----------------------------------------------------
START TRANSACTION;
USE `premiser`;
INSERT INTO `premiser`.`os` (`id`, `name`) VALUES (DEFAULT, 'ubuntu');

COMMIT;


-- -----------------------------------------------------
-- Data for table `premiser`.`os_version`
-- -----------------------------------------------------
START TRANSACTION;
USE `premiser`;
INSERT INTO `premiser`.`os_version` (`id`, `os_id`, `version`) VALUES (DEFAULT, 1, '14.04');
INSERT INTO `premiser`.`os_version` (`id`, `os_id`, `version`) VALUES (DEFAULT, 1, '16.04');
INSERT INTO `premiser`.`os_version` (`id`, `os_id`, `version`) VALUES (DEFAULT, 1, '18.04');
INSERT INTO `premiser`.`os_version` (`id`, `os_id`, `version`) VALUES (DEFAULT, 1, '20.04');
INSERT INTO `premiser`.`os_version` (`id`, `os_id`, `version`) VALUES (DEFAULT, 1, '22.04');

COMMIT;


-- -----------------------------------------------------
-- Data for table `premiser`.`framework_version`
-- -----------------------------------------------------
START TRANSACTION;
USE `premiser`;
INSERT INTO `premiser`.`framework_version` (`id`, `framework_id`, `version`) VALUES (DEFAULT, 1, '3.7');
INSERT INTO `premiser`.`framework_version` (`id`, `framework_id`, `version`) VALUES (DEFAULT, 1, '3.8');
INSERT INTO `premiser`.`framework_version` (`id`, `framework_id`, `version`) VALUES (DEFAULT, 1, '3.9');
INSERT INTO `premiser`.`framework_version` (`id`, `framework_id`, `version`) VALUES (DEFAULT, 1, '3.10');
INSERT INTO `premiser`.`framework_version` (`id`, `framework_id`, `version`) VALUES (DEFAULT, 2, '14');
INSERT INTO `premiser`.`framework_version` (`id`, `framework_id`, `version`) VALUES (DEFAULT, 2, '16');
INSERT INTO `premiser`.`framework_version` (`id`, `framework_id`, `version`) VALUES (DEFAULT, 2, '18');
INSERT INTO `premiser`.`framework_version` (`id`, `framework_id`, `version`) VALUES (DEFAULT, 2, '20');
INSERT INTO `premiser`.`framework_version` (`id`, `framework_id`, `version`) VALUES (DEFAULT, 3, '8.0');

COMMIT;


-- -----------------------------------------------------
-- Data for table `premiser`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `premiser`;
INSERT INTO `premiser`.`user` (`id`, `username`) VALUES (1, 'admin');

COMMIT;

